/**
 * Central Tool Registry — the single source of truth mapping every tool
 * slug to its category, engine, plan requirements, and SEO copy.
 *
 * Per the PRD's shared-engine model (Section 11.3): adding a tool means
 * adding an entry here plus its engine/schema/options-panel — the upload
 * pipeline, page template, and routing require zero changes per tool.
 */

export const CATEGORIES = {
  pdf: {
    slug: "pdf-tools",
    label: "PDF Tools",
    shortLabel: "PDF",
    description:
      "Merge, split, compress, and edit PDF files entirely in your browser — no files ever leave your device.",
  },
  image: {
    slug: "image-tools",
    label: "Image Tools",
    shortLabel: "Image",
    description:
      "Compress, resize, crop, and edit images in any format, processed locally for full privacy.",
  },
  imageConverter: {
    slug: "image-converter",
    label: "Image Converter",
    shortLabel: "Converter",
    description:
      "Convert between JPG, PNG, WEBP, HEIC, AVIF, GIF, BMP, TIFF, and SVG — pick an exact format pair or use the all-in-one converter.",
  },
  document: {
    slug: "document-tools",
    label: "Document Tools",
    shortLabel: "Document",
    description:
      "Convert between Word, Excel, PowerPoint, and PDF while preserving layout, fonts, and images.",
  },
  audio: {
    slug: "audio-tools",
    label: "Audio Tools",
    shortLabel: "Audio",
    description: "Trim, merge, split, and normalize audio files using a real FFmpeg engine in your browser.",
  },
  audioConverter: {
    slug: "audio-converter",
    label: "Audio Converter",
    shortLabel: "Converter",
    description:
      "Convert MP3, WAV, AAC, FLAC, OGG, and M4A, or pull the audio track out of a video file — pick an exact conversion or use the all-in-one converter.",
  },
  video: {
    slug: "video-tools",
    label: "Video Tools",
    shortLabel: "Video",
    description: "Compress, trim, resize, and edit video without uploading it anywhere.",
  },
  videoConverter: {
    slug: "video-converter",
    label: "Video Converter",
    shortLabel: "Converter",
    description:
      "Convert between MP4, AVI, MOV, MKV, WEBM, and animated GIF — pick an exact format pair or use the all-in-one converter.",
  },
  archive: {
    slug: "archive-tools",
    label: "Archive Tools",
    shortLabel: "Archive",
    description: "Create and extract ZIP, 7Z, TAR, GZ, and RAR archives, fully client-side.",
  },
};

/**
 * `status` field meaning:
 *  - "full": genuinely complete, no known fidelity gaps.
 *  - "partial": real and functional, with one specific, disclosed constraint
 *    (never a silent placeholder — the constraint is real-world and stated
 *    in the tool's own FAQ/UI copy, e.g. "RAR creation isn't a format
 *    7-Zip itself supports").
 */
export const TOOLS = [
  // ---------------------------------------------------------------- PDF
  {
    slug: "merge-pdf",
    category: "pdf",
    name: "Merge PDF",
    verb: "Merge",
    description: "Combine multiple PDF files into a single document, in any order you choose.",
    engine: "pdf",
    accepts: ["application/pdf"],
    multiple: true,
    minFiles: 2,
    status: "full",
  },
  {
    slug: "split-pdf",
    category: "pdf",
    name: "Split PDF",
    verb: "Split",
    description: "Extract pages from a PDF into separate files, by range, by count, or by bookmark.",
    engine: "pdf",
    accepts: ["application/pdf"],
    multiple: false,
    status: "full",
  },
  {
    slug: "compress-pdf",
    category: "pdf",
    name: "Compress PDF",
    verb: "Compress",
    description: "Shrink PDF file size by compressing embedded images and optimizing fonts.",
    engine: "pdf",
    accepts: ["application/pdf"],
    multiple: false,
    status: "full",
  },
  {
    slug: "rotate-pdf",
    category: "pdf",
    name: "Rotate PDF",
    verb: "Rotate",
    description: "Rotate every page or a chosen subset by 90, 180, or 270 degrees.",
    engine: "pdf",
    accepts: ["application/pdf"],
    multiple: false,
    status: "full",
  },
  {
    slug: "delete-pdf-pages",
    category: "pdf",
    name: "Delete Pages",
    verb: "Delete pages from",
    description: "Remove specific pages from a PDF using a visual thumbnail picker.",
    engine: "pdf",
    accepts: ["application/pdf"],
    multiple: false,
    status: "full",
  },
  {
    slug: "extract-pdf-pages",
    category: "pdf",
    name: "Extract Pages",
    verb: "Extract pages from",
    description: "Pull selected pages out of a PDF into a brand-new document.",
    engine: "pdf",
    accepts: ["application/pdf"],
    multiple: false,
    status: "full",
  },
  {
    slug: "rearrange-pdf-pages",
    category: "pdf",
    name: "Rearrange Pages",
    verb: "Rearrange",
    description: "Drag pages into a new order, duplicate, or delete them, all in one workflow.",
    engine: "pdf",
    accepts: ["application/pdf"],
    multiple: false,
    status: "full",
  },
  {
    slug: "watermark-pdf",
    category: "pdf",
    name: "Watermark PDF",
    verb: "Watermark",
    description: "Stamp a text or image watermark across every page, with full control over position and opacity.",
    engine: "pdf",
    accepts: ["application/pdf"],
    multiple: false,
    status: "full",
  },
  {
    slug: "password-protect-pdf",
    category: "pdf",
    name: "Password Protect PDF",
    verb: "Password protect",
    description: "Encrypt a PDF with a password and set printing, copying, and editing permissions.",
    engine: "pdf",
    accepts: ["application/pdf"],
    multiple: false,
    status: "full",
  },
  {
    slug: "unlock-pdf",
    category: "pdf",
    name: "Unlock PDF",
    verb: "Unlock",
    description: "Remove password protection from a PDF you have the password for.",
    engine: "pdf",
    accepts: ["application/pdf"],
    multiple: false,
    status: "full",
    requiresPassword: true,
  },
  {
    slug: "number-pdf-pages",
    category: "pdf",
    name: "Number Pages",
    verb: "Add page numbers to",
    description: "Add page numbers with your choice of position, font, and starting number.",
    engine: "pdf",
    accepts: ["application/pdf"],
    multiple: false,
    status: "full",
  },
  {
    slug: "crop-pdf",
    category: "pdf",
    name: "Crop PDF",
    verb: "Crop",
    description: "Trim margins from a PDF manually or automatically detect and remove whitespace.",
    engine: "pdf",
    accepts: ["application/pdf"],
    multiple: false,
    status: "full",
  },
  {
    slug: "repair-pdf",
    category: "pdf",
    name: "Repair PDF",
    verb: "Repair",
    description: "Attempt structural recovery of a damaged or corrupted PDF file.",
    engine: "pdf",
    accepts: ["application/pdf"],
    multiple: false,
    status: "full",
  },
  {
    slug: "ocr-pdf",
    category: "pdf",
    name: "OCR PDF",
    verb: "Run OCR on",
    description: "Turn scanned PDFs into searchable, selectable text using real optical character recognition.",
    engine: "ocr",
    accepts: ["application/pdf"],
    multiple: false,
    status: "full",
  },
  {
    slug: "sign-pdf",
    category: "pdf",
    name: "Sign PDF",
    verb: "Sign",
    description: "Add a drawn, typed, or uploaded signature anywhere on a document.",
    engine: "pdf",
    accepts: ["application/pdf"],
    multiple: false,
    status: "full",
  },
  {
    slug: "fill-pdf-forms",
    category: "pdf",
    name: "Fill PDF Forms",
    verb: "Fill out",
    description: "Detect and fill interactive PDF form fields, then flatten or keep them editable.",
    engine: "pdf",
    accepts: ["application/pdf"],
    multiple: false,
    status: "full",
  },

  // -------------------------------------------------------------- Image
  {
    slug: "convert-image",
    category: "imageConverter",
    name: "All-in-One Image Converter",
    verb: "Convert",
    description: "Convert between PNG, JPG, WEBP, AVIF, BMP, TIFF, GIF, SVG, ICO, and HEIC — choose any target format.",
    engine: "image",
    accepts: ["image/*"],
    multiple: true,
    status: "full",
  },
  {
    slug: "jpg-to-png",
    category: "imageConverter",
    name: "JPG to PNG",
    verb: "Convert",
    description: "Convert JPG photos to lossless, transparency-capable PNG files.",
    engine: "image",
    accepts: [".jpg", ".jpeg"],
    multiple: true,
    status: "full",
    targetFormat: "png",
  },
  {
    slug: "png-to-jpg",
    category: "imageConverter",
    name: "PNG to JPG",
    verb: "Convert",
    description: "Convert PNG images to smaller, widely-compatible JPG files.",
    engine: "image",
    accepts: [".png"],
    multiple: true,
    status: "full",
    targetFormat: "jpg",
  },
  {
    slug: "jpg-to-webp",
    category: "imageConverter",
    name: "JPG to WEBP",
    verb: "Convert",
    description: "Convert JPG photos to WebP for smaller file sizes with comparable quality.",
    engine: "image",
    accepts: [".jpg", ".jpeg"],
    multiple: true,
    status: "full",
    targetFormat: "webp",
  },
  {
    slug: "webp-to-png",
    category: "imageConverter",
    name: "WEBP to PNG",
    verb: "Convert",
    description: "Convert WebP images to universally-compatible PNG files.",
    engine: "image",
    accepts: [".webp"],
    multiple: true,
    status: "full",
    targetFormat: "png",
  },
  {
    slug: "heic-to-jpg",
    category: "imageConverter",
    name: "HEIC to JPG",
    verb: "Convert",
    description: "Convert iPhone HEIC photos to JPG files that open anywhere.",
    engine: "image",
    accepts: [".heic", ".heif"],
    multiple: true,
    status: "full",
    targetFormat: "jpg",
  },
  {
    slug: "png-to-webp",
    category: "imageConverter",
    name: "PNG to WEBP",
    verb: "Convert",
    description: "Convert PNG images to WebP for a smaller file size while keeping transparency.",
    engine: "image",
    accepts: [".png"],
    multiple: true,
    status: "full",
    targetFormat: "webp",
  },
  {
    slug: "svg-to-png",
    category: "imageConverter",
    name: "SVG to PNG",
    verb: "Convert",
    description: "Convert scalable SVG vector graphics into a fixed-resolution PNG.",
    engine: "image",
    accepts: [".svg"],
    multiple: true,
    status: "full",
    targetFormat: "png",
  },
  {
    slug: "avif-to-jpg",
    category: "imageConverter",
    name: "AVIF to JPG",
    verb: "Convert",
    description: "Convert modern AVIF images to widely-compatible JPG files.",
    engine: "image",
    accepts: [".avif"],
    multiple: true,
    status: "full",
    targetFormat: "jpg",
  },
  {
    slug: "gif-to-png",
    category: "imageConverter",
    name: "GIF to PNG",
    verb: "Convert",
    description: "Convert a GIF's first frame into a static PNG image.",
    engine: "image",
    accepts: [".gif"],
    multiple: true,
    status: "full",
    targetFormat: "png",
  },
  {
    slug: "bmp-to-jpg",
    category: "imageConverter",
    name: "BMP to JPG",
    verb: "Convert",
    description: "Convert uncompressed BMP images into much smaller JPG files.",
    engine: "image",
    accepts: [".bmp"],
    multiple: true,
    status: "full",
    targetFormat: "jpg",
  },
  {
    slug: "tiff-to-jpg",
    category: "imageConverter",
    name: "TIFF to JPG",
    verb: "Convert",
    description: "Convert TIFF images into smaller, universally-supported JPG files.",
    engine: "image",
    accepts: [".tif", ".tiff"],
    multiple: true,
    status: "full",
    targetFormat: "jpg",
  },
  {
    slug: "compress-image",
    category: "image",
    name: "Compress Image",
    verb: "Compress",
    description: "Reduce image file size with adjustable quality, from lossless to maximum compression.",
    engine: "image",
    accepts: ["image/*"],
    multiple: true,
    status: "full",
  },
  {
    slug: "resize-image",
    category: "image",
    name: "Resize Image",
    verb: "Resize",
    description: "Resize by exact dimensions or percentage, with an optional aspect-ratio lock.",
    engine: "image",
    accepts: ["image/*"],
    multiple: true,
    status: "full",
  },
  {
    slug: "crop-image",
    category: "image",
    name: "Crop Image",
    verb: "Crop",
    description: "Crop freely or to a preset aspect ratio using a visual selector.",
    engine: "image",
    accepts: ["image/*"],
    multiple: false,
    status: "full",
  },
  {
    slug: "rotate-flip-image",
    category: "image",
    name: "Rotate & Flip Image",
    verb: "Rotate or flip",
    description: "Rotate in 90-degree steps and flip horizontally or vertically.",
    engine: "image",
    accepts: ["image/*"],
    multiple: true,
    status: "full",
  },
  {
    slug: "watermark-image",
    category: "image",
    name: "Watermark Image",
    verb: "Watermark",
    description: "Overlay a text or image watermark with control over opacity, rotation, and shadow.",
    engine: "image",
    accepts: ["image/*"],
    multiple: true,
    status: "full",
  },
  {
    slug: "remove-background",
    category: "image",
    name: "Remove Background",
    verb: "Remove the background from",
    description: "Automatically remove the background from a photo, outputting a transparent PNG.",
    engine: "image",
    accepts: ["image/*"],
    multiple: false,
    status: "full",
  },
  {
    slug: "image-metadata",
    category: "image",
    name: "Image Metadata",
    verb: "Inspect metadata in",
    description: "View camera, GPS, and color-profile metadata, with a one-click option to strip it.",
    engine: "image",
    accepts: ["image/*"],
    multiple: false,
    status: "full",
  },
  {
    slug: "convert-image-to-pdf",
    category: "image",
    name: "Image to PDF",
    verb: "Convert to PDF",
    description: "Combine one or more images into a single PDF with custom margins and orientation.",
    engine: "image",
    accepts: ["image/*"],
    multiple: true,
    status: "full",
  },

  // ----------------------------------------------------------- Document
  {
    slug: "word-to-pdf",
    category: "document",
    name: "Word to PDF",
    verb: "Convert",
    description: "Convert DOCX to PDF while preserving fonts, images, tables, and layout exactly.",
    engine: "document",
    accepts: [".docx"],
    multiple: false,
    status: "full",
  },
  {
    slug: "pdf-to-word",
    category: "document",
    name: "PDF to Word",
    verb: "Convert",
    description: "Convert PDF into an editable Word document, reconstructing text, images, and tables in place.",
    engine: "document",
    accepts: ["application/pdf"],
    multiple: false,
    status: "full",
  },
  {
    slug: "excel-to-pdf",
    category: "document",
    name: "Excel to PDF",
    verb: "Convert",
    description: "Convert spreadsheets to PDF with correct page breaks and print scaling.",
    engine: "document",
    accepts: [".xlsx", ".xls", ".csv"],
    multiple: false,
    status: "full",
  },
  {
    slug: "pdf-to-excel",
    category: "document",
    name: "PDF to Excel",
    verb: "Convert",
    description: "Extract tables from a PDF into an editable spreadsheet.",
    engine: "document",
    accepts: ["application/pdf"],
    multiple: false,
    status: "full",
  },
  {
    slug: "powerpoint-to-pdf",
    category: "document",
    name: "PowerPoint to PDF",
    verb: "Convert",
    description: "Convert presentations to PDF, preserving slide layout and optional speaker notes.",
    engine: "document",
    accepts: [".pptx"],
    multiple: false,
    status: "full",
  },
  {
    slug: "pdf-to-powerpoint",
    category: "document",
    name: "PDF to PowerPoint",
    verb: "Convert",
    description: "Turn PDF pages into editable presentation slides.",
    engine: "document",
    accepts: ["application/pdf"],
    multiple: false,
    status: "full",
  },
  {
    slug: "txt-to-pdf",
    category: "document",
    name: "TXT to PDF",
    verb: "Convert",
    description: "Convert plain text into a cleanly formatted PDF.",
    engine: "document",
    accepts: [".txt"],
    multiple: false,
    status: "full",
  },
  {
    slug: "html-to-pdf",
    category: "document",
    name: "HTML to PDF",
    verb: "Convert",
    description: "Render an HTML file into a PDF, preserving structure and styling.",
    engine: "document",
    accepts: [".html", ".htm"],
    multiple: false,
    status: "full",
  },
  {
    slug: "markdown-to-pdf",
    category: "document",
    name: "Markdown to PDF",
    verb: "Convert",
    description: "Render Markdown, including headings, lists, tables, and code blocks, into a styled PDF.",
    engine: "document",
    accepts: [".md", ".markdown"],
    multiple: false,
    status: "full",
  },

  // -------------------------------------------------------------- Audio
  {
    slug: "convert-audio",
    category: "audioConverter",
    name: "All-in-One Audio Converter",
    verb: "Convert",
    description: "Convert between MP3, WAV, AAC, FLAC, OGG, M4A, AIFF, and AMR — choose any target format.",
    engine: "media",
    accepts: ["audio/*"],
    multiple: false,
    status: "full",
  },
  {
    slug: "trim-audio",
    category: "audio",
    name: "Trim Audio",
    verb: "Trim",
    description: "Cut an audio file down to a selected start and end point.",
    engine: "media",
    accepts: ["audio/*"],
    multiple: false,
    status: "full",
  },
  {
    slug: "normalize-audio",
    category: "audio",
    name: "Normalize Audio",
    verb: "Normalize",
    description: "Even out volume to a consistent, target loudness level.",
    engine: "media",
    accepts: ["audio/*"],
    multiple: false,
    status: "full",
  },
  {
    slug: "merge-audio",
    category: "audio",
    name: "Merge Audio",
    verb: "Merge",
    description: "Combine multiple audio files into a single continuous track.",
    engine: "media",
    accepts: ["audio/*"],
    multiple: true,
    minFiles: 2,
    status: "full",
  },
  {
    slug: "split-audio",
    category: "audio",
    name: "Split Audio",
    verb: "Split",
    description: "Split one audio file into several segments at chosen timestamps.",
    engine: "media",
    accepts: ["audio/*"],
    multiple: false,
    status: "full",
  },
  {
    slug: "extract-audio-from-video",
    category: "audioConverter",
    name: "Extract Audio from Video",
    verb: "Extract audio from",
    description: "Pull just the audio track out of a video file — the tool behind MP4 to MP3 and every other video-to-audio conversion.",
    engine: "media",
    accepts: ["video/*"],
    multiple: false,
    status: "full",
  },
  {
    slug: "mp4-to-mp3",
    category: "audioConverter",
    name: "MP4 to MP3",
    verb: "Extract audio from",
    description: "Pull the MP3 audio track out of an MP4 video file.",
    engine: "media",
    accepts: [".mp4"],
    multiple: false,
    status: "full",
    targetFormat: "mp3",
  },
  {
    slug: "mov-to-mp3",
    category: "audioConverter",
    name: "MOV to MP3",
    verb: "Extract audio from",
    description: "Pull the MP3 audio track out of a MOV video file, like footage recorded on an iPhone.",
    engine: "media",
    accepts: [".mov"],
    multiple: false,
    status: "full",
    targetFormat: "mp3",
  },
  {
    slug: "wav-to-mp3",
    category: "audioConverter",
    name: "WAV to MP3",
    verb: "Convert",
    description: "Convert uncompressed WAV audio into much smaller MP3 files.",
    engine: "media",
    accepts: [".wav"],
    multiple: false,
    status: "full",
    targetFormat: "mp3",
  },
  {
    slug: "mp3-to-wav",
    category: "audioConverter",
    name: "MP3 to WAV",
    verb: "Convert",
    description: "Convert MP3 files to uncompressed WAV audio for editing or production use.",
    engine: "media",
    accepts: [".mp3"],
    multiple: false,
    status: "full",
    targetFormat: "wav",
  },

  // -------------------------------------------------------------- Video
  {
    slug: "convert-video",
    category: "videoConverter",
    name: "All-in-One Video Converter",
    verb: "Convert",
    description: "Convert between MP4, AVI, MOV, MKV, WEBM, and animated GIF — choose any target format.",
    engine: "media",
    accepts: ["video/*"],
    multiple: false,
    status: "full",
  },
  {
    slug: "mov-to-mp4",
    category: "videoConverter",
    name: "MOV to MP4",
    verb: "Convert",
    description: "Convert MOV video from an iPhone or camera into universally-compatible MP4.",
    engine: "media",
    accepts: [".mov"],
    multiple: false,
    status: "full",
    targetFormat: "mp4",
  },
  {
    slug: "mp4-to-gif",
    category: "videoConverter",
    name: "MP4 to GIF",
    verb: "Convert",
    description: "Turn a short MP4 clip into a shareable animated GIF.",
    engine: "media",
    accepts: [".mp4"],
    multiple: false,
    status: "full",
    targetFormat: "gif",
  },
  {
    slug: "avi-to-mp4",
    category: "videoConverter",
    name: "AVI to MP4",
    verb: "Convert",
    description: "Convert older AVI video files into modern, widely-supported MP4.",
    engine: "media",
    accepts: [".avi"],
    multiple: false,
    status: "full",
    targetFormat: "mp4",
  },
  {
    slug: "mkv-to-mp4",
    category: "videoConverter",
    name: "MKV to MP4",
    verb: "Convert",
    description: "Convert MKV video files into MP4 for broader device and platform support.",
    engine: "media",
    accepts: [".mkv"],
    multiple: false,
    status: "full",
    targetFormat: "mp4",
  },
  {
    slug: "compress-video",
    category: "video",
    name: "Compress Video",
    verb: "Compress",
    description: "Shrink video file size with a configurable target quality and bitrate.",
    engine: "media",
    accepts: ["video/*"],
    multiple: false,
    status: "full",
  },
  {
    slug: "resize-video",
    category: "video",
    name: "Resize Video",
    verb: "Resize",
    description: "Change video resolution to a standard preset or custom dimensions.",
    engine: "media",
    accepts: ["video/*"],
    multiple: false,
    status: "full",
  },
  {
    slug: "trim-video",
    category: "video",
    name: "Trim Video",
    verb: "Trim",
    description: "Cut a video down to a selected time range.",
    engine: "media",
    accepts: ["video/*"],
    multiple: false,
    status: "full",
  },
  {
    slug: "crop-video",
    category: "video",
    name: "Crop Video",
    verb: "Crop",
    description: "Crop the video frame to a selected region.",
    engine: "media",
    accepts: ["video/*"],
    multiple: false,
    status: "full",
  },
  {
    slug: "change-video-fps",
    category: "video",
    name: "Change Video FPS",
    verb: "Change the frame rate of",
    description: "Retarget a video's frame rate up or down.",
    engine: "media",
    accepts: ["video/*"],
    multiple: false,
    status: "full",
  },
  {
    slug: "watermark-video",
    category: "video",
    name: "Watermark Video",
    verb: "Watermark",
    description: "Overlay a text or image watermark on a video.",
    engine: "media",
    accepts: ["video/*"],
    multiple: false,
    status: "full",
  },
  {
    slug: "rotate-video",
    category: "video",
    name: "Rotate Video",
    verb: "Rotate",
    description: "Rotate a video in 90-degree increments.",
    engine: "media",
    accepts: ["video/*"],
    multiple: false,
    status: "full",
  },

  // ------------------------------------------------------------ Archive
  {
    slug: "create-archive",
    category: "archive",
    name: "Create Archive",
    verb: "Compress",
    description: "Compress one or more files into a ZIP, 7Z, TAR, or GZ archive.",
    engine: "archive",
    accepts: ["*"],
    multiple: true,
    minFiles: 1,
    status: "full",
  },
  {
    slug: "extract-archive",
    category: "archive",
    name: "Extract Archive",
    verb: "Extract",
    description: "Extract the contents of a ZIP, RAR, 7Z, TAR, or GZ archive.",
    engine: "archive",
    accepts: [".zip", ".rar", ".7z", ".tar", ".gz"],
    multiple: false,
    status: "full",
  },
];

export const toolBySlug = new Map(TOOLS.map((t) => [t.slug, t]));

export function getTool(slug) {
  return toolBySlug.get(slug) ?? null;
}

export function getToolsByCategory(category) {
  return TOOLS.filter((t) => t.category === category);
}

export function getAllToolSlugs() {
  return TOOLS.map((t) => t.slug);
}

export function getCategoryBySlug(categorySlug) {
  const entry = Object.entries(CATEGORIES).find(([, v]) => v.slug === categorySlug);
  return entry ? { key: entry[0], ...entry[1] } : null;
}

export function getRelatedTools(slug, limit = 4) {
  const tool = getTool(slug);
  if (!tool) return [];
  return TOOLS.filter((t) => t.category === tool.category && t.slug !== slug).slice(0, limit);
}
