import {
  HiOutlineSquares2X2,
  HiOutlineScissors,
  HiOutlineArrowsPointingIn,
  HiOutlineArrowPath,
  HiOutlineDocumentMinus,
  HiOutlineDocumentPlus,
  HiOutlineBars3BottomLeft,
  HiOutlinePencilSquare,
  HiOutlineLockClosed,
  HiOutlineLockOpen,
  HiOutlineNumberedList,
  HiOutlineViewfinderCircle,
  HiOutlineWrenchScrewdriver,
  HiOutlineDocumentMagnifyingGlass,
  HiOutlineIdentification,
  HiOutlineClipboardDocumentCheck,
  HiOutlineArrowsRightLeft,
  HiOutlineArchiveBoxArrowDown,
  HiOutlinePhoto,
  HiOutlineRectangleGroup,
  HiOutlineArrowUpTray,
  HiOutlineSparkles,
  HiOutlineInformationCircle,
  HiOutlineDocument,
  HiOutlineDocumentText,
  HiOutlineTableCells,
  HiOutlinePresentationChartBar,
  HiOutlineCodeBracket,
  HiOutlineMusicalNote,
  HiOutlineSpeakerWave,
  HiOutlineScissors as HiOutlineScissors2,
  HiOutlineFilm,
  HiOutlineArrowsPointingOut,
  HiOutlineVideoCamera,
  HiOutlineArchiveBox,
  HiOutlineArchiveBoxXMark,
  HiOutlineDocumentDuplicate,
  HiOutlineViewColumns,
  HiOutlineDocumentCheck,
  HiOutlineCommandLine,
  HiOutlineSwatch,
  HiOutlineWindow,
  HiOutlineForward,
  HiOutlineArrowUturnLeft,
  HiOutlineLanguage,
  HiOutlineChartBar,
  HiOutlineListBullet,
} from "react-icons/hi2";

export const TOOL_ICONS = {
  "merge-pdf": HiOutlineSquares2X2,
  "split-pdf": HiOutlineScissors,
  "compress-pdf": HiOutlineArrowsPointingIn,
  "rotate-pdf": HiOutlineArrowPath,
  "delete-pdf-pages": HiOutlineDocumentMinus,
  "extract-pdf-pages": HiOutlineDocumentPlus,
  "rearrange-pdf-pages": HiOutlineBars3BottomLeft,
  "watermark-pdf": HiOutlinePencilSquare,
  "password-protect-pdf": HiOutlineLockClosed,
  "unlock-pdf": HiOutlineLockOpen,
  "number-pdf-pages": HiOutlineNumberedList,
  "crop-pdf": HiOutlineViewfinderCircle,
  "repair-pdf": HiOutlineWrenchScrewdriver,
  "ocr-pdf": HiOutlineDocumentMagnifyingGlass,
  "sign-pdf": HiOutlineIdentification,
  "fill-pdf-forms": HiOutlineClipboardDocumentCheck,
  "pdf-to-jpg": HiOutlinePhoto,
  "pdf-to-png": HiOutlinePhoto,
  "compare-pdf": HiOutlineDocumentDuplicate,
  "pdf-page-layout": HiOutlineViewColumns,
  "pdf-to-pdfa": HiOutlineDocumentCheck,

  "convert-image": HiOutlineArrowsRightLeft,
  "compress-image": HiOutlineArchiveBoxArrowDown,
  "resize-image": HiOutlineArrowsPointingOut,
  "crop-image": HiOutlineRectangleGroup,
  "rotate-flip-image": HiOutlineArrowPath,
  "watermark-image": HiOutlinePencilSquare,
  "remove-background": HiOutlineSparkles,
  "image-metadata": HiOutlineInformationCircle,
  "convert-image-to-pdf": HiOutlineDocument,
  "png-to-ico": HiOutlineWindow,
  "jpg-to-pdf": HiOutlineDocument,
  "avif-to-png": HiOutlinePhoto,
  "heic-to-png": HiOutlinePhoto,
  "webp-to-avif": HiOutlinePhoto,
  "image-to-ascii": HiOutlineCommandLine,
  "add-image-border": HiOutlineViewfinderCircle,
  "image-color-palette": HiOutlineSwatch,
  "image-to-base64": HiOutlineCommandLine,
  "image-upscaler": HiOutlineArrowsPointingOut,

  "word-to-pdf": HiOutlineDocumentText,
  "pdf-to-word": HiOutlineDocumentText,
  "excel-to-pdf": HiOutlineTableCells,
  "pdf-to-excel": HiOutlineTableCells,
  "pdf-to-csv": HiOutlineTableCells,
  "csv-to-excel": HiOutlineTableCells,
  "word-to-excel": HiOutlineTableCells,
  "pdf-to-markdown": HiOutlineCommandLine,
  "merge-word": HiOutlineDocumentDuplicate,
  "powerpoint-to-pdf": HiOutlinePresentationChartBar,
  "pdf-to-powerpoint": HiOutlinePresentationChartBar,
  "txt-to-pdf": HiOutlineDocument,
  "html-to-pdf": HiOutlineCodeBracket,
  "markdown-to-pdf": HiOutlineCodeBracket,

  "convert-audio": HiOutlineMusicalNote,
  "trim-audio": HiOutlineScissors2,
  "normalize-audio": HiOutlineSpeakerWave,
  "merge-audio": HiOutlineSquares2X2,
  "split-audio": HiOutlineScissors2,
  "audio-speed-changer": HiOutlineForward,
  "audio-pitch-changer": HiOutlineMusicalNote,
  "audio-volume-changer": HiOutlineSpeakerWave,
  "reverse-audio": HiOutlineArrowUturnLeft,
  "audio-fade": HiOutlineSpeakerWave,
  "extract-audio-from-video": HiOutlineMusicalNote,
  "flac-to-mp3": HiOutlineMusicalNote,
  "ogg-to-mp3": HiOutlineMusicalNote,
  "m4a-to-mp3": HiOutlineMusicalNote,
  "aac-to-mp3": HiOutlineMusicalNote,
  "mp3-to-ogg": HiOutlineMusicalNote,

  "convert-video": HiOutlineFilm,
  "webm-to-mp4": HiOutlineFilm,
  "mp4-to-webm": HiOutlineFilm,
  "mov-to-webm": HiOutlineFilm,
  "mkv-to-avi": HiOutlineFilm,
  "gif-to-mp4": HiOutlineFilm,
  "compress-video": HiOutlineArchiveBoxArrowDown,
  "resize-video": HiOutlineArrowsPointingOut,
  "trim-video": HiOutlineScissors2,
  "crop-video": HiOutlineRectangleGroup,
  "change-video-fps": HiOutlineVideoCamera,
  "watermark-video": HiOutlinePencilSquare,
  "rotate-video": HiOutlineArrowPath,
  "merge-videos": HiOutlineFilm,
  "add-subtitles": HiOutlineLanguage,
  "video-to-waveform": HiOutlineChartBar,
  "extract-video-frame": HiOutlinePhoto,
  "video-speed-changer": HiOutlineForward,

  "create-archive": HiOutlineArchiveBox,
  "extract-archive": HiOutlineArchiveBoxXMark,
  "add-to-archive": HiOutlineArchiveBox,
  "password-protect-archive": HiOutlineLockClosed,
  "convert-archive": HiOutlineArrowsRightLeft,
  "list-archive-contents": HiOutlineListBullet,
  "split-archive": HiOutlineSquares2X2,
};

export function getToolIcon(slug) {
  return TOOL_ICONS[slug] || HiOutlineDocument;
}
