import {
  HiOutlineSquares2X2,
  HiOutlineScissors,
  HiOutlineArrowsPointingIn,
  HiOutlineArrowPath,
  HiOutlineDocumentMinus,
  HiOutlineDocumentPlus,
  HiOutlineBars3BottomLeft,
  HiOutlinePencilSquare,
  HiOutlineLockClosed,
  HiOutlineLockOpen,
  HiOutlineNumberedList,
  HiOutlineViewfinderCircle,
  HiOutlineWrenchScrewdriver,
  HiOutlineDocumentMagnifyingGlass,
  HiOutlineIdentification,
  HiOutlineClipboardDocumentCheck,
  HiOutlineArrowsRightLeft,
  HiOutlineArchiveBoxArrowDown,
  HiOutlinePhoto,
  HiOutlineRectangleGroup,
  HiOutlineArrowUpTray,
  HiOutlineSparkles,
  HiOutlineInformationCircle,
  HiOutlineDocument,
  HiOutlineDocumentText,
  HiOutlineTableCells,
  HiOutlinePresentationChartBar,
  HiOutlineCodeBracket,
  HiOutlineMusicalNote,
  HiOutlineSpeakerWave,
  HiOutlineScissors as HiOutlineScissors2,
  HiOutlineFilm,
  HiOutlineArrowsPointingOut,
  HiOutlineVideoCamera,
  HiOutlineArchiveBox,
  HiOutlineArchiveBoxXMark,
} from "react-icons/hi2";

export const TOOL_ICONS = {
  "merge-pdf": HiOutlineSquares2X2,
  "split-pdf": HiOutlineScissors,
  "compress-pdf": HiOutlineArrowsPointingIn,
  "rotate-pdf": HiOutlineArrowPath,
  "delete-pdf-pages": HiOutlineDocumentMinus,
  "extract-pdf-pages": HiOutlineDocumentPlus,
  "rearrange-pdf-pages": HiOutlineBars3BottomLeft,
  "watermark-pdf": HiOutlinePencilSquare,
  "password-protect-pdf": HiOutlineLockClosed,
  "unlock-pdf": HiOutlineLockOpen,
  "number-pdf-pages": HiOutlineNumberedList,
  "crop-pdf": HiOutlineViewfinderCircle,
  "repair-pdf": HiOutlineWrenchScrewdriver,
  "ocr-pdf": HiOutlineDocumentMagnifyingGlass,
  "sign-pdf": HiOutlineIdentification,
  "fill-pdf-forms": HiOutlineClipboardDocumentCheck,

  "convert-image": HiOutlineArrowsRightLeft,
  "compress-image": HiOutlineArchiveBoxArrowDown,
  "resize-image": HiOutlineArrowsPointingOut,
  "crop-image": HiOutlineRectangleGroup,
  "rotate-flip-image": HiOutlineArrowPath,
  "watermark-image": HiOutlinePencilSquare,
  "remove-background": HiOutlineSparkles,
  "image-metadata": HiOutlineInformationCircle,
  "convert-image-to-pdf": HiOutlineDocument,

  "word-to-pdf": HiOutlineDocumentText,
  "pdf-to-word": HiOutlineDocumentText,
  "excel-to-pdf": HiOutlineTableCells,
  "pdf-to-excel": HiOutlineTableCells,
  "powerpoint-to-pdf": HiOutlinePresentationChartBar,
  "pdf-to-powerpoint": HiOutlinePresentationChartBar,
  "txt-to-pdf": HiOutlineDocument,
  "html-to-pdf": HiOutlineCodeBracket,
  "markdown-to-pdf": HiOutlineCodeBracket,

  "convert-audio": HiOutlineMusicalNote,
  "trim-audio": HiOutlineScissors2,
  "normalize-audio": HiOutlineSpeakerWave,
  "merge-audio": HiOutlineSquares2X2,
  "split-audio": HiOutlineScissors2,
  "extract-audio-from-video": HiOutlineMusicalNote,

  "convert-video": HiOutlineFilm,
  "compress-video": HiOutlineArchiveBoxArrowDown,
  "resize-video": HiOutlineArrowsPointingOut,
  "trim-video": HiOutlineScissors2,
  "crop-video": HiOutlineRectangleGroup,
  "change-video-fps": HiOutlineVideoCamera,
  "watermark-video": HiOutlinePencilSquare,
  "rotate-video": HiOutlineArrowPath,

  "create-archive": HiOutlineArchiveBox,
  "extract-archive": HiOutlineArchiveBoxXMark,
};

export function getToolIcon(slug) {
  return TOOL_ICONS[slug] || HiOutlineDocument;
}
