import { comparePdfs } from "@/lib/engines/pdf/compare-pdf";
import { ComparePdfOptionsPanel } from "./options-panel";

function escapeHtml(str) {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

/**
 * Builds a single, self-contained HTML file (inline CSS, no external
 * requests) so the diff report opens correctly offline and the added/
 * removed line styling survives being saved and reopened later, rather
 * than downloading as plain unstyled text.
 */
function buildDiffReportHtml(result, fileNameA, fileNameB, onlyChangedPages) {
  const pages = onlyChangedPages ? result.pages.filter((p) => p.changeCount > 0) : result.pages;

  const pageSections = pages
    .map((page) => {
      const lines = page.diff
        .map((entry) => {
          const cls = entry.type === "added" ? "added" : entry.type === "removed" ? "removed" : "same";
          const marker = entry.type === "added" ? "+" : entry.type === "removed" ? "\u2212" : "\u00a0";
          return `<div class="line ${cls}"><span class="marker">${marker}</span>${escapeHtml(entry.text)}</div>`;
        })
        .join("\n");
      const note = !page.inA ? " (only in File B)" : !page.inB ? " (only in File A)" : "";
      return `<section class="page"><h2>Page ${page.pageNum}${note}</h2><div class="lines">${lines}</div></section>`;
    })
    .join("\n");

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<title>PDF Comparison — ${escapeHtml(fileNameA)} vs ${escapeHtml(fileNameB)}</title>
<style>
  body { font-family: -apple-system, Segoe UI, sans-serif; max-width: 900px; margin: 40px auto; padding: 0 20px; color: #18181b; }
  h1 { font-size: 20px; }
  .meta { color: #71717a; font-size: 14px; margin-bottom: 24px; }
  .page { margin-bottom: 28px; }
  .page h2 { font-size: 14px; color: #71717a; font-weight: 600; margin-bottom: 6px; }
  .lines { border: 1px solid #e4e4e7; border-radius: 10px; padding: 8px; background: #fafafa; }
  .line { font-family: ui-monospace, SFMono-Regular, monospace; font-size: 12px; padding: 3px 6px; border-radius: 5px; white-space: pre-wrap; word-break: break-word; }
  .marker { display: inline-block; width: 16px; opacity: 0.6; }
  .line.added { background: #d1fae5; color: #065f46; }
  .line.removed { background: #fee2e2; color: #991b1b; text-decoration: line-through; text-decoration-color: rgba(153,27,27,0.4); }
  .line.same { color: #71717a; }
</style>
</head>
<body>
  <h1>PDF Comparison</h1>
  <p class="meta">
    <strong>${escapeHtml(fileNameA)}</strong> (${result.pageCountA} pages) vs
    <strong>${escapeHtml(fileNameB)}</strong> (${result.pageCountB} pages)
    &mdash; ${result.totalChanges} line change${result.totalChanges === 1 ? "" : "s"} total.
    Generated by Tools Root's Compare PDF, entirely in-browser.
  </p>
  ${pageSections || "<p>No changed pages to show.</p>"}
</body>
</html>`;
}

export const comparePdfAdapter = {
  accepts: ["application/pdf"],
  multiple: true,
  minFiles: 2,
  OptionsPanel: ComparePdfOptionsPanel,
  defaultOptions: { onlyChangedPages: true },
  runButtonLabel: "Download comparison report",
  async run(files, options, onProgress) {
    onProgress({ stage: "Comparing pages", value: 0.1 });
    const result = await comparePdfs(files[0], files[1], (p) =>
      onProgress({ stage: "Comparing pages", value: 0.1 + p * 0.8 })
    );
    onProgress({ stage: "Building report", value: 0.95 });
    const html = buildDiffReportHtml(result, files[0].name, files[1].name, options.onlyChangedPages ?? true);
    const blob = new Blob([html], { type: "text/html" });
    onProgress({ stage: "Done", value: 1 });
    return [{ blob, name: "pdf-comparison-report.html" }];
  },
};
